services:
  product-service:
    build: .
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=postgres-product
      - DB_PORT=5432
      - DB_NAME=productdb
      - DB_USER=postgres
      - DB_PASS=postgres
      - ES_URIS=http://ecommerce-elasticsearch:9200
      - ES_INDEX_PREFIX=product
      - RABBITMQ_HOST=ecommerce-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=ecommerce_admin
      - RABBITMQ_PASSWORD=EcommerceSecurePass2026!
      - REDIS_HOST=ecommerce-redis
      - REDIS_PORT=6379
      - REDIS_DATABASE=1
      - SPRING_AUTOCONFIGURE_EXCLUDE=org.springframework.modulith.events.amqp.RabbitJackson2Configuration
    depends_on:
      postgres-product:
        condition: service_healthy
    networks:
      - ecommerce-shared-network

  postgres-product:
    image: postgres:16-alpine
    container_name: postgres-product
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5437:5432"
    volumes:
      - pg-product-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d productdb"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - ecommerce-shared-network

volumes:
  pg-product-data:

networks:
  ecommerce-shared-network:
    external: true