name: Auth Service CI

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - 'auth-service/**'
      - '.github/workflows/auth-service-ci.yml'
  pull_request:
    branches: [ "main", "master" ]
    paths:
      - 'auth-service/**'
      - '.github/workflows/auth-service-ci.yml'

jobs:
  test-and-build:
    name: Run Unit & Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Kodu GitHub'dan Çek
        uses: actions/checkout@v4

      - name: Java JDK Kurulumu
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Spring Boot Testlerini Çalıştır
        # working-directory parametresini doğrudan adımın altına aldık
        working-directory: auth-service
        run: mvn test -Dspring.profiles.active=test